@SETLOCAL
@IF NOT DEFINED NODE_PATH (
  @SET "NODE_PATH=C:\Users\HP\Downloads\bhoomi-sentinel-updated\bhoomi-sentinel\node_modules\.pnpm\pnpm@10.18.0\node_modules\pnpm\bin\node_modules;C:\Users\HP\Downloads\bhoomi-sentinel-updated\bhoomi-sentinel\node_modules\.pnpm\pnpm@10.18.0\node_modules\pnpm\node_modules;C:\Users\HP\Downloads\bhoomi-sentinel-updated\bhoomi-sentinel\node_modules\.pnpm\pnpm@10.18.0\node_modules;C:\Users\HP\Downloads\bhoomi-sentinel-updated\bhoomi-sentinel\node_modules\.pnpm\node_modules"
) ELSE (
  @SET "NODE_PATH=C:\Users\HP\Downloads\bhoomi-sentinel-updated\bhoomi-sentinel\node_modules\.pnpm\pnpm@10.18.0\node_modules\pnpm\bin\node_modules;C:\Users\HP\Downloads\bhoomi-sentinel-updated\bhoomi-sentinel\node_modules\.pnpm\pnpm@10.18.0\node_modules\pnpm\node_modules;C:\Users\HP\Downloads\bhoomi-sentinel-updated\bhoomi-sentinel\node_modules\.pnpm\pnpm@10.18.0\node_modules;C:\Users\HP\Downloads\bhoomi-sentinel-updated\bhoomi-sentinel\node_modules\.pnpm\node_modules;%NODE_PATH%"
)
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\pnpm\bin\pnpx.cjs" %*
) ELSE (
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\pnpm\bin\pnpx.cjs" %*
)
